/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PasskeyImport } from './routes/passkey'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PasskeyRoute = PasskeyImport.update({
  id: '/passkey',
  path: '/passkey',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/passkey': {
      id: '/passkey'
      path: '/passkey'
      fullPath: '/passkey'
      preLoaderRoute: typeof PasskeyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/passkey': typeof PasskeyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/passkey': typeof PasskeyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/passkey': typeof PasskeyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/passkey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/passkey'
  id: '__root__' | '/' | '/passkey'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PasskeyRoute: typeof PasskeyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PasskeyRoute: PasskeyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/passkey"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/passkey": {
      "filePath": "passkey.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
