/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PasskeyRouteImport } from './routes/passkey'
import { Route as IndexRouteImport } from './routes/index'

const PasskeyRoute = PasskeyRouteImport.update({
  id: '/passkey',
  path: '/passkey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/passkey': typeof PasskeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/passkey': typeof PasskeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/passkey': typeof PasskeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/passkey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/passkey'
  id: '__root__' | '/' | '/passkey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PasskeyRoute: typeof PasskeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/passkey': {
      id: '/passkey'
      path: '/passkey'
      fullPath: '/passkey'
      preLoaderRoute: typeof PasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PasskeyRoute: PasskeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
