import {
  Connection,
  Keypair,
  LAMPORTS_PER_SOL,
  SystemProgram,
  Transaction,
  TransactionInstruction,
} from '@solana/web3.js';
import {
  Actions,
  createEd25519AuthorityInfo,
  fetchSwig,
  findSwigPda,
  findSwigSubAccountPda,
  getAddAuthorityInstructions,
  getCreateSubAccountInstructions,
  getCreateSwigInstruction,
  getSignInstructions,
} from '@swig-wallet/classic';
import {
  createMint,
  getAssociatedTokenAddressSync,
  createAssociatedTokenAccountInstruction,
  mintTo,
  TOKEN_PROGRAM_ID,
} from '@solana/spl-token';

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function randomBytes(length: number): Uint8Array {
  const randomArray = new Uint8Array(length);
  crypto.getRandomValues(randomArray);
  return randomArray;
}

async function sendTransaction(
  connection: Connection,
  instructions: TransactionInstruction[],
  payer: Keypair,
  signers: Keypair[] = [],
): Promise<string> {
  const tx = new Transaction().add(...instructions);
  tx.feePayer = payer.publicKey;
  tx.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;
  tx.sign(payer, ...signers);
  const signature = await connection.sendRawTransaction(tx.serialize());
  await connection.confirmTransaction(signature, 'confirmed');
  return signature;
}

(async () => {
  const connection = new Connection('http://localhost:8899', 'confirmed');

  // === Setup root Swig ===
  const rootAuthority = Keypair.generate();
  await connection.requestAirdrop(rootAuthority.publicKey, 2 * LAMPORTS_PER_SOL);
  await sleep(2000);

  const swigId = randomBytes(32);
  const swigAddress = findSwigPda(swigId);
  console.log('🧱 Swig Root Address:', swigAddress.toBase58());

  const createSwigIx = await getCreateSwigInstruction({
    payer: rootAuthority.publicKey,
    actions: Actions.set().all().get(),
    authorityInfo: createEd25519AuthorityInfo(rootAuthority.publicKey),
    id: swigId,
  });

  const swigTx = await sendTransaction(connection, [createSwigIx], rootAuthority);
  console.log(`📝 Root Swig creation tx: https://explorer.solana.com/tx/${swigTx}?cluster=custom`);

  await sleep(1500);
  const swig = await fetchSwig(connection, swigAddress);
  const rootRole = swig.findRolesByEd25519SignerPk(rootAuthority.publicKey)[0];

  // === Create a real SPL Token mint and SWIG's ATA ===
  const decimals = 6; // adjust if you want
  const tokenMint = await createMint(
    connection,
    rootAuthority,               // payer
    rootAuthority.publicKey,     // mint authority
    rootAuthority.publicKey,     // freeze authority (optional)
    decimals,
    undefined,                   // keypair (autogenerated)
    { commitment: 'confirmed' }, // confirm opts
    TOKEN_PROGRAM_ID
  );
  console.log('🪙 Created test SPL mint:', tokenMint.toBase58());

  // Create SWIG PDA's ATA for this mint (owner-off-curve allowed)
  const swigAta = getAssociatedTokenAddressSync(
    tokenMint,
    swigAddress,
    true // allowOwnerOffCurve for PDA owners
  );
  const createAtaIx = createAssociatedTokenAccountInstruction(
    rootAuthority.publicKey, // payer
    swigAta,
    swigAddress,
    tokenMint
  );
  await sendTransaction(connection, [createAtaIx], rootAuthority);
  console.log('🏦 Created SWIG ATA:', swigAta.toBase58());

  // Optional but helpful: mint a tiny balance so indexer 100% sees it
  const amountForAta = 10n * BigInt(10 ** decimals); // 10 tokens
  await mintTo(
    connection,
    rootAuthority,           // payer
    tokenMint,               // mint
    swigAta,                 // destination ATA
    rootAuthority,           // mint authority signer
    Number(amountForAta)
  );
  console.log('💧 Minted to SWIG ATA:', amountForAta.toString());

  // === Add multiple roles (use the REAL token mint) ===
  const roleKeypairs: Record<string, Keypair> = {};
  const roleConfigs = [
    { name: 'data-entry', amount: 0.05, tokenLimit: 100 },
    { name: 'finance', amount: 0.1, tokenLimit: 200 },
    { name: 'developer', amount: 0.2, tokenLimit: 500 },
    { name: 'moderator', amount: 0.05, tokenLimit: 50 },
  ];

  const ONE_DAY_SECS = 86400;

  for (const { name, amount, tokenLimit } of roleConfigs) {
    const roleKeypair = Keypair.generate();
    const builder = Actions.set()
      .solLimit({ amount: BigInt(Math.floor(amount * LAMPORTS_PER_SOL)) })
      .tokenLimit({ mint: tokenMint, amount: BigInt(tokenLimit) })
      .solRecurringLimit({
        recurringAmount: BigInt(amount * LAMPORTS_PER_SOL),
        window: BigInt(ONE_DAY_SECS),
      });

    // Token recurring limit currently appears to be unsupported by the deployed on-chain program.
    // Keeping this line for future enablement; comment out to avoid simulation failure until program upgraded.
  const enableTokenRecurring = false; // set true when on-chain program supports TokenRecurringLimit
    if (enableTokenRecurring) {
      builder.tokenReccuringLimit({
        mint: tokenMint,
        recurringAmount: BigInt(tokenLimit),
        window: BigInt(ONE_DAY_SECS),
      });
    }

    const actions = builder.get();

    // Debug: dump action buffer & interpreted permissions before sending
    const raw = actions.bytes();
    const perms: number[] = [];
    // Each header is 8 bytes: u16 permission, u16 length, u32 boundary
    for (let cursor = 0; cursor < raw.length; ) {
      const dv = new DataView(raw.buffer, raw.byteOffset + cursor, 8);
      const permission = dv.getUint16(0, true);
      // const length = dv.getUint16(2, true); // not needed for debugging
      const boundary = dv.getUint32(4, true);
      perms.push(permission);
      cursor = boundary; // jump to next header
      if (boundary === 0 || boundary > raw.length) break; // safety
    }
    console.log(`🔍 Actions for role '${name}': permissions=${perms.join(',')} totalBytes=${raw.length}`);

    const addRoleIx = await getAddAuthorityInstructions(
      swig,
      rootRole.id,
      createEd25519AuthorityInfo(roleKeypair.publicKey),
      actions,
    );

    try {
      await sendTransaction(connection, addRoleIx, rootAuthority);
    } catch (e: any) {
      console.error(`❌ Failed creating role '${name}' (permissions=${perms.join(',')}):`, e?.message);
      console.error('   Hint: If permission 6 (TokenRecurringLimit) appears, the local swig program may not support it yet.');
      throw e; // rethrow to stop script
    }
    roleKeypairs[name] = roleKeypair;

    console.log(`✅ Created role "${name}"`);
    console.log(`   🔑 Public Key: ${roleKeypair.publicKey.toBase58()}`);
  }

  // === Add subaccount authority ===
  const subAccountAuthority = Keypair.generate();
  await connection.requestAirdrop(subAccountAuthority.publicKey, LAMPORTS_PER_SOL);
  await sleep(2000);

  const addSubAccountAuthorityIx = await getAddAuthorityInstructions(
    swig,
    rootRole.id,
    createEd25519AuthorityInfo(subAccountAuthority.publicKey),
    Actions.set().subAccount().get(),
  );

  await sendTransaction(connection, addSubAccountAuthorityIx, rootAuthority);

  await sleep(1500);
  await swig.refetch();
  const subAccountRole = swig.findRolesByEd25519SignerPk(subAccountAuthority.publicKey)[0];

  // === Create subaccount ===
  const createSubAccountIx = await getCreateSubAccountInstructions(
    swig,
    subAccountRole.id,
  );
  await sendTransaction(connection, createSubAccountIx, subAccountAuthority);

  await sleep(1500);
  await swig.refetch();

  const subAccountAddress = findSwigSubAccountPda(
    subAccountRole.swigId,
    subAccountRole.id,
  );

  console.log('📦 Subaccount Address:', subAccountAddress.toBase58());

  await connection.requestAirdrop(subAccountAddress, LAMPORTS_PER_SOL);
  await sleep(1500);

  console.log(
    '💰 Subaccount balance:',
    await connection.getBalance(subAccountAddress),
  );

  // === Transfer from subaccount ===
  const recipient = Keypair.generate().publicKey;
  const transferIx = SystemProgram.transfer({
    fromPubkey: subAccountAddress,
    toPubkey: recipient,
    lamports: 0.1 * LAMPORTS_PER_SOL,
  });

  const signIx = await getSignInstructions(
    swig,
    subAccountRole.id,
    [transferIx],
    true, // subaccount
  );

  const tx = await sendTransaction(connection, signIx, subAccountAuthority);
  console.log(`🚀 Subaccount transfer tx: https://explorer.solana.com/tx/${tx}?cluster=custom`);

  const recipientBalance = await connection.getBalance(recipient);
  console.log('💸 Recipient balance after transfer:', recipientBalance);
})();
